services:
  backend:
    build: ./backend
    container_name: laravel_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/var/www/html
      - /var/www/html/vendor
    working_dir: /var/www/html
    command: php artisan serve --host=0.0.0.0 --port=8000
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: vue_frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    working_dir: /app
    command: yarn dev --host
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
